layout_spectrum: 0.2929755
typography_spectrum: 0.06820623
color:
  saturation: 0.1925438
  lightness: 0.2537147
  brandStrength: 0.6875064
  brandColors:
    - '#000000'
    - '#ECEEE1'
    - '#C1B4AB'
    - '#897C73'
    - '#3F3D4A'
  rhythmicContrast: 0.6918033
name: DFMO
