typography_spectrum: 0.06820623
color:
  saturation: 0.1925438
  lightness: 0.2537147
  brandStrength: 0.6875064
  brandColors:
    - '#000000'
    - '#ECEEE1'
    - '#C1B4AB'
    - '#897C73'
    - '#3F3D4A'
  rhythmicContrast: 0.6918033
layout_spectrum: 0.2929755
author:
  email: dfmomusic@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54447b2e-aaf0-46a9-8e14-6263e081418f.jpg
name: DFMO
navigation:
  - name: On Facebook
    url: 'https://facebook.com/thedfmo'
    type: external
title: DFMO
description: DJ / Producer
