author:
  email: dfmomusic@gmail.com
title: DFMO
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b403146a-fa96-4e3a-8bf9-ac12271b91f9.png
description: DJ / Producer
color:
  saturation: 0.8432393509428948
  brandStrength: 0.5193341
  lightness: 0.3073166601825505
  brandColors:
    - '#01204B'
    - '#FFFFFF'
    - '#026A86'
    - '#0293A7'
    - '#A1AF99'
  rhythmicContrast: 0.5430975372437388
typography_spectrum: 0.5998926
navigation:
  - name: Follow
    url: 'https://facebook.com/thedfmo'
    type: external
  - name: Listen
    url: 'https://mixcloud.com/dfmo'
    type: external
layout_spectrum: 1
name: DFMO
